// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NyiratiBalint_WebAPI.Data;

#nullable disable

namespace NyiratiBalint_WebAPI.Migrations
{
    [DbContext(typeof(SzerzodesDbContext))]
    partial class SzerzodesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NyiratiBalint_WebAPI.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PartnerNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partnerek", (string)null);
                });

            modelBuilder.Entity("NyiratiBalint_WebAPI.Models.Szerzodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IgazgatoJovahagyta")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("SzerzodesSzam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SzerzodesTargya")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Szerzodesek", (string)null);
                });

            modelBuilder.Entity("NyiratiBalint_WebAPI.Models.Szerzodes", b =>
                {
                    b.HasOne("NyiratiBalint_WebAPI.Models.Partner", "Partner")
                        .WithMany("Szerzodes")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("NyiratiBalint_WebAPI.Models.Partner", b =>
                {
                    b.Navigation("Szerzodes");
                });
#pragma warning restore 612, 618
        }
    }
}
